apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
data:
  NODE_ENV: "{{ .Values.config.NODE_ENV }}"
  PORT: "{{ .Values.config.PORT }}"
  OPENMRS_URL: "{{ .Values.config.OPENMRS_URL }}"
  TEMPLATES_DIR: "{{ .Values.config.TEMPLATES_DIR }}"
  TZ: "{{ .Values.global.TZ }}"
  PDF_ENABLED: "{{ .Values.config.PDF_ENABLED }}"
  MAX_CONCURRENT_PDF: "{{ .Values.config.MAX_CONCURRENT_PDF }}"
  NUNJUCKS_CACHE: "{{ .Values.config.NUNJUCKS_CACHE }}"