name: Build and Publish

on:
  push:
    branches:
      - main
      - BAH-4868
      - 'release-*'
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    name: Lint, Test & Build
    runs-on: ubuntu-latest
    outputs:
      artifact_version: ${{ steps.version.outputs.artifact_version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set env.ARTIFACT_VERSION
        id: version
        run: |
          wget -q https://raw.githubusercontent.com/Bahmni/bahmni-infra-utils/main/setArtifactVersion.sh && chmod +x setArtifactVersion.sh
          ./setArtifactVersion.sh .appversion
          rm setArtifactVersion.sh
          echo "artifact_version=$ARTIFACT_VERSION" >> $GITHUB_OUTPUT

      - name: Setup Node.js 24.x
        uses: actions/setup-node@v6
        with:
          node-version: "24.x"
          cache: "yarn"

      - run: yarn install --frozen-lockfile

      - run: yarn lint

      - run: yarn test

      - run: yarn build

  build-publish-docker:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        include:
          - with_pdf: "false"
            tag_suffix: ""
            build_name: "Docker Build (without PDF support)"
          - with_pdf: "true"
            tag_suffix: "-pdf"
            build_name: "Docker Build (with PDF support)"
    name: ${{ matrix.build_name }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Login to DockerHub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Docker - Build and push
        uses: docker/build-push-action@v7
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: Dockerfile
          build-args: WITH_PDF=${{ matrix.with_pdf }}
          push: true
          tags: |
            bahmni/bahmni-template-service:${{ needs.build.outputs.artifact_version }}${{ matrix.tag_suffix }}
            bahmni/bahmni-template-service:latest${{ matrix.tag_suffix }}

  publish-helm:
    name: Publish Helm Chart
    runs-on: ubuntu-latest
    needs: [build, build-publish-docker]
    env:
      HELM_CHART_PATH: package/helm/
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Update Version and Image Tag
        run: |
          yq --inplace '.image.tag = "${{ needs.build.outputs.artifact_version }}"' $HELM_CHART_PATH/values.yaml
          yq --inplace '.version = "${{ needs.build.outputs.artifact_version }}"' $HELM_CHART_PATH/Chart.yaml

      - name: Helm Lint
        run: helm lint $HELM_CHART_PATH

      - name: Helm Package
        run: helm package $HELM_CHART_PATH

      - name: Checkout Charts Repository
        uses: actions/checkout@v4
        with:
          repository: Bahmni/helm-charts
          ref: gh-pages
          path: helm-charts
          persist-credentials: false

      - name: Copy Helm Archive
        run: mkdir -p helm-charts/template-service/ && cp template-service-${{ needs.build.outputs.artifact_version }}.tgz helm-charts/template-service/

      - name: Helm Index
        working-directory: helm-charts/
        run: helm repo index --merge index.yaml --url https://bahmni.github.io/helm-charts/  .

      - name: Commit and Push Chart Repository
        working-directory: helm-charts/
        run: |
          git config user.name ${{ secrets.BAHMNI_USERNAME}}
          git config user.email ${{ secrets.BAHMNI_EMAIL}}
          git add .
          git commit -m "Release of template-service-${{ needs.build.outputs.artifact_version }}"
          git push 'https://${{ secrets.BAHMNI_USERNAME}}:${{ secrets.BAHMNI_PAT}}@github.com/bahmni/helm-charts.git' gh-pages
